#define FAIL_CONF \
  "impossible d'ouvrir le fichier de configuration en écriture dans la fonction Enregistrer la configuration"
#define mDNS_Responder_Started "mDNS responder démarré"
#define Reason_for_reset "-- Raison du redémarrage: %d --"
#define Start_filesystem "Démarrage du système de fichiers"
#define Load_configuration "Chargement de la configuration"
#define Load_configuration_loaded "Configuration chargée"
#define Load_configuration_failed_use_default \
  "Échec du chargement du fichier de configuration, utilisation de la configuration par défaut"
#define Save_configuration_saved "Configuration sauvegardée"
#define Save_configuration_failed_open \
  "Échec de sauvegarde de la configuration : impossible d'ouvrir le fichier de configuration"
#define Save_configuration_failed_write \
  "Échec de sauvegarde de la configuration : impossible d'écrire dans le fichier de configuration"
#define Load_configuration_MQTT "Chargement de la configuration MQTT"
#define Loading_wifi_configuration "Chargement de la configuration wifi"
#define Loading_minuterie "Chargement de la minuterie"
#define Start_Wifiautoconnect "Démarrage de Wifiautoconnect"
#define DALLAS_detected "%d DALLAS détecté"
#define Attempting_MQTT_connexion "Tentative de connexion MQTT"
#define End_Start "Fin du démarrage"
#define Stop_minuteur "Arrêt du minuteur"
#define Start_minuteur "Démarrage du minuteur"
#define Stop_minuteur_relay1 "Arrêt du relay1"
#define Start_minuteur_relay1 "Démarrage du relay1"
#define Stop_minuteur_relay2 "Arrêt du relay2"
#define Start_minuteur_relay2 "Démarrage du relay2"
#define Alert_Temp "Alerte Température"
#define Child_at_zero "Enfant à 0"
#define Alerte_Dallas_not_found "Alerte Dallas non trouvée"
#define Dallas_Dallas_master_not_found "Dallas Maitre non trouvée"
#define Dallas_lost "Dallas perdue"
#define HTTP_power_at "HTTP puissance à"
#define FS_version_is_missing "FS version manquante, veuillez mettre à jour"
#define FS_version_is_outdated "La version du FS n'est pas à jour"
#define FS_version_is_uptodate "La version du FS est à jour"
#define Failed_write_wifi_config "Impossible d'écrire la configuration wifi"
#define Clear_alarm_temp "retrait de l'alarme de température"
#define Subscribe_MQTT "S'abonner et publier sur les sujets MQTT"
#define Dallas_sensor "Sonde Dallas "
#define found_Address " trouvée. Adresse : "
#define Dallas_sensor_found "Sonde Dallas %d trouvée. Adresse : %s"
#define Dallas_sensor_is_main "La sonde Dallas %s est la sonde principale"
#define Dallas_sensor_is_now_main "La sonde Dallas %s est désormais la sonde principale"
#define Connecting_MQTT "Connexion à MQTT... "
#define MQTT_connected "MQTT connecté"