#define FAIL_CONF "Failed to open configuration file for writing in SaveConfig function"
#define mDNS_Responder_Started "mDNS responder started"
#define Reason_for_reset "-- Reason for reset: %d --"
#define Start_filesystem "Starting the filesystem"
#define Load_configuration "Loading configuration"
#define Load_configuration_loaded "Configuration loaded"
#define Load_configuration_failed_use_default "Failed to load configuration file, use default"
#define Save_configuration_saved "Configuration saved"
#define Save_configuration_failed_open "Failed to save configuration: can't open configuration file"
#define Save_configuration_failed_write "Failed to save configuration: can't write the configuration file"
#define Load_configuration_MQTT "Chargement de la configuration MQTT"
#define Loading_wifi_configuration "Loading WiFi configuration"
#define Loading_minuterie "Loading timer"
#define Start_Wifiautoconnect "Starting WiFi autoconnect"
#define DALLAS_detected "%d DALLAS detected"
#define Attempting_MQTT_connexion "Attempting MQTT connection"
#define End_Start "Startup complete"
#define Stop_minuteur "Stopping timer"
#define Start_minuteur "Starting timer"
#define Alert_Temp "Temperature alert"
#define Child_at "Child at"
#define Alerte_Dallas_not_found "Dallas alert not found"
#define Dallas_Dallas_master_not_found "Dallas master not found"
#define Dallas_sensor_found "Dallas sensor %d found. Address: %s"
#define Dallas_sensor_is_main "Dallas sensor %s is the main one"
#define Dallas_sensor_is_now_main "Dallas sensor %s is now the main one"
#define Dallas_lost "Dallas lost"
#define HTTP_power_at "HTTP power at"
#define FS_version_is_missing "FS version missing, please update it."
#define FS_version_is_outdated "FS version is outdated, please update it."
#define FS_version_is_uptodate "FS version is up to date"
