#define FAIL_CONF "не вдалося відкрити файл конфігурації для запису у функції Зберегти конфігурацію"
#define mDNS_Responder_Started "mDNS responder запущено"
#define Reason_for_reset "Причина перезавантаження: "
#define Start_filesystem "Запуск файлової системи"
#define Load_configuration "Завантаження конфігурації"
#define Loading_wifi_configuration "Завантаження конфігурації WiFi"
#define Loading_minuterie "Завантаження таймера"
#define Start_Wifiautoconnect "Запуск WiFi автопідключення"
#define DALLAS_detected "DALLAS виявлено"
#define Attempting_MQTT_connexion "Спроба підключення до MQTT"
#define End_Start "Запуск завершено"
#define Stop_minuteur "Зупинка таймера"
#define Start_minuteur "Запуск таймера"
#define Alert_Temp "Температурна тривога"
#define Child_at "Дитина біля"
#define Alerte_Dallas_not_found "Тривога: Dallas не знайдено"
#define Dallas_Dallas_master_not_found "Майстер Dallas не знайдено"
#define found_Address "знайдено. Адреса:"
#define Dallas_lost "Dallas втрачено"
#define HTTP_power_at "HTTP потужність на"
#define FS_version_is_missing "Версія FS відсутня, будь ласка, оновіть"
#define FS_version_is_outdated "Версія FS не актуальна"
#define FS_version_is_uptodate "Версія FS актуальна"
